# Generated by Django 5.1 on 2024-08-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageupload",
            name="uploaded_at",
        ),
        migrations.AlterField(
            model_name="imageupload",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
