# Generated by Django 5.1 on 2024-08-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_remove_imageupload_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageupload",
            name="image",
            field=models.ImageField(
                upload_to="C:/Users/varun/PycharmProjects/Image3D/pixel2shape/media/uploads/"
            ),
        ),
    ]
